/* Compact investigation, rendered from the same bulletin as the headline. */
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = value => Number(value).toLocaleString('en-US');
const link = (url, label = 'Source') => /^https:\/\//.test(url || '') ? `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>` : '';
const card = (label, value, detail = '', metric = '', figure = null) => `<article class="brief-card"><span class="brief-label">${esc(label)}</span><strong${metric ? ` ${metric.startsWith('response:') ? 'data-response' : 'data-figure'}="${metric.replace('response:','')}"` : ''}>${esc(value)}</strong>${detail ? `<p>${esc(detail)}</p>` : ''}${figure ? `<small class="metric-source" data-source-for="${metric}">${link(figure.url,figure.source?.split(' · ')[0] || 'Source')}</small>` : ''}</article>`;
export function renderInvestigation(event, sources) {
  const figures = event.figures || {};
  const response = event.response || {};
  const d = event.districts || { rows: [] };
  const stat = label => event.stats.find(s => s.label === label)?.value || '—';
  const districts = d.rows.map(row => `<div class="district-row"><span>${esc(row.district)}</span><span class="district-track"><i style="width:${Math.round(row.value / Math.max(...d.rows.map(r => r.value)) * 100)}%"></i></span><b>${number(row.value)}</b></div>`).join('');
  const groups = sources.map(g => `<div class="source-group"><h4>${esc(g.title)}</h4><div>${g.links.map(([url, name]) => link(url, name)).join('')}</div></div>`).join('');
  const responseCards = [
    ['People in holding centres', response.sheltered, 'Rasuwa · Nuwakot · Dhading', 'sheltered'],
    ['Injured', response.injured, '', 'injured'],
    ['Discharged from care', response.discharged, '', 'discharged'],
    ['Holding centres', response.centres, '', 'centres'],
    ['Receiving hospital care', response.inHospital, '', 'inHospital']
  ].filter(([,value]) => Number.isFinite(value)).slice(0,4)
    .map(([label,value,detail,metric]) => card(label,number(value),detail,`response:${metric}`)).join('');
  const operations = response.personnel ? `<section class="brief-section" id="inv-response"><div class="brief-heading"><h3>Rescue & shelter</h3><span data-response-stamp>${esc(new Date(response.time).toLocaleString('en-GB',{timeZone:'Asia/Kathmandu',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))} NPT · ${link(response.url)}</span></div><div class="response-layout"><div class="brief-grid">${responseCards}</div><article class="response-team"><span class="brief-label">Search & relief teams</span><strong data-response="personnel">${number(response.personnel)}</strong><dl><div><dt>Nepali Army</dt><dd data-response="army">${number(response.army)}</dd></div><div><dt>Nepal Police</dt><dd data-response="police">${number(response.police)}</dd></div><div><dt>Armed Police Force</dt><dd data-response="apf">${number(response.apf)}</dd></div></dl></article></div></section>` : '';
  return `<div class="investigation-dashboard">
    <section class="brief-section" id="inv-board"><div class="brief-heading"><h3>The situation</h3><time data-board-time>${esc(new Date(event.asOf).toLocaleString('en-GB',{timeZone:'Asia/Kathmandu',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))} NPT</time></div><div class="situation-grid">${card('Bodies recovered',stat('confirmed dead'),'','dead',figures.dead)}${card('Listed missing',stat('listed missing in Nepal'),'List under verification','missing',figures.missing)}${card('People rescued',stat('rescued so far'),'','rescued',figures.rescued)}${card('Identified & handed over',number(response.identified || 0),'','response:identified',response)}</div><div class="brief-meta">${link(figures.dead?.url || d.url,event.asOfSource || 'Sources')}<span>Missing does not mean confirmed dead.</span></div></section>
    <div class="investigation-pair"><section class="brief-section" id="inv-dist"><div class="brief-heading"><h3>Where deaths were recorded</h3><span><b data-district-total>${number(d.total)}</b> accounted for</span></div><div class="district-list" data-investigation-districts>${districts}</div><div class="brief-meta"><span data-district-source>${link(d.url)}</span><span>Eight recovery districts + hospital deaths</span></div></section><section class="brief-section field-guide"><div class="brief-heading"><h3>Find someone. Get help.</h3></div><a href="https://rescue.opmcm.gov.np/" target="_blank" rel="noopener"><span>Missing & rescued people</span><strong>Search the official register ↗</strong></a><a href="https://udb.nepalpolice.gov.np/disaster" target="_blank" rel="noopener"><span>Identification</span><strong>Nepal Police records ↗</strong></a><a href="tel:100"><span>Emergency assistance</span><strong>Call Nepal Police · 100</strong></a><a href="https://www.mofa.gov.np/category/flashflood/" target="_blank" rel="noopener"><span>Foreign nationals & families</span><strong>Ministry of Foreign Affairs ↗</strong></a></section></div>
    ${operations}
    <section class="brief-section" id="inv-damage"><div class="brief-heading"><h3>Damage & access</h3><a href="#map" data-tab-link="map">Open map ↗</a></div><div class="damage-grid"><article class="place-card"><span class="brief-label">Rasuwa · Nuwakot</span><h4>River corridor</h4><p>Roads, bridges and hydropower facilities damaged.</p>${link('https://nirajbhusal.github.io/rasuwa-flood-bulletin/notices.html','Current road notices')}</article><article class="place-card"><span class="brief-label">Government notices</span><h4>Road access</h4><p>Check open routes and limits before travelling.</p>${link('https://nirajbhusal.github.io/rasuwa-flood-bulletin/notices.html')}</article><article class="place-card"><span class="brief-label">Satellite assessment</span><h4>Buildings & roads</h4><p>View mapped damage by location.</p>${link('https://mapping.emergency.copernicus.eu/activations/EMSR927/','Copernicus maps')}</article></div><div class="restoration"><div><h4>Electricity restored</h4><span data-response-source>${link(response.url)}</span></div>${(response.electricity || []).map(r=>`<div><span>${esc(r.place)}</span><strong data-electricity="${esc(r.place)}">${r.value}%</strong><progress max="100" value="${r.value}" aria-label="Electricity restored in ${esc(r.place)}"></progress></div>`).join('')}</div></section>
    <section class="brief-section sources-section" id="inv-sources"><div class="brief-heading"><h3>Sources</h3><a href="/investigation.json">Download data ↗</a></div>${groups}</section></div>`;
}
